@startuml Основной процесс взаимодействия

start 
:Пользователь зашел на сайт;

if (Есть ли у пользователя аккаунт?) then (да)
else (нет)  
    :Регистрация;
endif
:Авторизация;
switch ()
    case (Домовладелец)
        :Отображение страницы с графиком потребления энергии (то что есть сейчас в бд);
        repeat :Запрос на обновление данных;
        :Обновление отображения данных;
        repeat while (Прошло 5 минут?) is (нет) not (да)

        if (Есть рекомендации или запрос на получение рекомендаций?) then (нет)
        else (да)  
            :Отправить уведомление о наличие рекомендаций пользователю;
            :Отобразить рекомендации;
        endif

        :Настроить лимиты;
        if (Есть превышение лимитов?) then (нет)
        else (да)  
            :Отправить уведомление о превышение лимитов пользователю;
            :Отобразить уведомление;
        endif
        
        :Подготовить отчет по потреблению;
        :Экспортировать отчет;
        stop

    '    
    case (Компания)
        :Отображение страницы с графиком потребления энергии (то что есть сейчас в бд);
        repeat :Запрос на обновление данных;
        :Обновление отображения данных;
        repeat while (Прошло 30 минут?) is (нет) not (да)

        if (Есть запрос на получение прогнозов потребления?) then (нет)
        else (да)  
            :Отправить уведомление о подготовке прогноза;
            :Отобразить прогноз;
        endif

        :Экспортировать прогноз или данные;
        stop

    '
    case (Тех персонал)
        :Отобразить страницу с прекрепленными к нему датчиками и их состояниями;
        
        repeat :Запрос на обновление данных;
        :Обновление отображения данных;
        repeat while (Прошла 1 минута?) is (нет) not (да)

        if (Есть датчики не в статусе ok или поступил запрос/задача на выполнение работ?) then (нет)
        else (да)  
            :Отправить уведомление о наличие датчика в не ok состояние или есть задача;
            :Сформулировать задачу;
            :Назначить задачу;
            :Отправить уведомление;
            :Прикрепить отчет о выполнение задачи;
            :Сохранить отчет;
            :Экспортировать отчет;
        endif

        :создать отчет о состояние датчиков;
        :Экспортировать отчет;
        stop

    '
    case (Администратор) 
        :Отображение страницы с графиком потребления энергии по датчикам(то что есть сейчас в бд);
        repeat :Запрос на обновление данных;
        :Обновление отображения данных;
        repeat while (Прошло 5 минут?) is (нет) not (да)

        if (Есть запрос на получение рейтинга потребления?) then (нет)
        else (да)  
            :Отправить уведомление о готовности рейтинга;
            :Отправить уведомление;
        endif

        :Настроить лимиты;
        if (Есть превышение лимитов?) then (нет)
        else (да)  
            :Отправить уведомление о превышение лимитов пользователю;
            :Отобразить уведомление;
        endif

        if (Есть запрос на получение прогнозов потребления?) then (нет)
        else (да)  
            :Отправить уведомление о подготовке прогноза;
            :Отобразить прогноз;
        endif
        
        :Подготовить отчет по потреблению;
        :Экспортировать отчет;
        stop
    endswitch
@enduml