@startuml Energy Consumption Accounting System Web App. Диаграмма контекста

' C4
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' Sprites
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl ICONURL/common.puml

' limit text width
skinparam wrapWidth 250
skinparam wrapMessageWidth 200

'
title "Energy Consumption Accounting System Web App. Диаграмма контекста"

' Personas 
Person(compUser, "Компания", "Добавляет пути получения данных, анализ данных о потреблении, формирование тарифов, планирование мощностей")
Person(adminUser, "Администратор промышленных обьектов", "Отчеты о потреблении, оптимизация производственных процессов, планирование бюджета")
Person(techUser, "Технический персонал", "Учет и обслуживание оборудования для мониторинга, решение технических проблем.")
Person(ownerUser, "Домовладелец", "Мониторинг и анализ потребления электроэнергии, получение рекомендаций по снижению расходов.")

System(mySystem, "Система учета энергопотребления", "Optional Description")
    compUser --> mySystem: ""
    adminUser --> mySystem: ""
    techUser --> mySystem: ""
    ownerUser --> mySystem: ""

' External System
System_Ext(extUserCheck, "сервис Проверка ИНН", "Проверка пользователей")
System_Ext(extPactCheck, "Проверка договоров на поставку электроэнергии", "Проверка договоров")
System_Ext(extEmail, "Доставка уведомлений",  "Отправка уведомлений.")
System_Ext(extData, "Предоставление данных", "Получение данных от и о счетчиках.")
    mySystem ---> extUserCheck : ""
    mySystem ---> extPactCheck : ""
    mySystem ---> extEmail : ""
    mySystem ---> extData : ""
@enduml